# use pip to import <pip install>
import time
import datetime
import platform
import psutil
from colorama import Fore
current_time = datetime.datetime.now()
# Printing attributes of now().
print("#" * 54)
print("HELLO FROM LOGIC SYSTEMS AND JACOB LODICE            ")
print("GATHERING TIME AND DATE                              ")
print("PLEASE WAIT...                                       ")
print("#" * 54)
time.sleep(3)
print("VERSON   :  1.20.1                                        ")
print('CPU USAGE: ', psutil.cpu_percent(4))
print('RAM memory % used:', psutil.virtual_memory()[2])
print('RAM Used (GB):', psutil.virtual_memory()[3]/1000000000)
print("#" * 54)
time.sleep(5)
print("#" * 54)
print("CURRENT TIME DATE AND YEAR:                          ")
print("#" * 54)
print("Year        ", current_time.year)
time.sleep(1)  
print("Month       ", current_time.month)              
time.sleep(1)
print("Day         ", current_time.day)                 
time.sleep(1)
print("Hour        ", current_time.hour)                
time.sleep(1)
print("Minute      ", current_time.minute)              
time.sleep(1)
print("Second      ", current_time.second)              
time.sleep(1)
print("Microsecond ", current_time.microsecond)         
time.sleep(1)
print("#" * 54)
time.sleep(2)
print("BULIT BY JACOB LODICE                               ")
print("#" * 54)
print(Fore.YELLOW + "CAUTION!: BIOS HAS BEEN ALTERD TAKE CAUTION WHEN USING CUSTEM BIOS")
time.sleep(1)
print(Fore.GREEN +  "STAT    : LOOKING FOR BOOTABLE .ISO")
time.sleep(5)
print(Fore.RED +    "ERROR   : NO BOOTABLE OS FOUND SYSTEM HULTED")